### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#1]
I suggest you to use the Papirus icon theme as a reference, they’ve been doing a good progress and the theme is getting very beautiful.
[Papirus Theme Github](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)

**Comment by ArtyomZorin** [comment]
Thanks for your suggestion! We have included a number of icons from the Papirus icon theme in the latest release.
