### ISSUE TITLE
Suggestion remove pycharm icon

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#14]
Pycharm icon is outdated, is better to remove from the theme and let show the original icon.
![pycharm](https://user-images.githubusercontent.com/31783838/115969659-66597600-a514-11eb-8fc6-36a1471599ff.png)

Current icon:
![download](https://user-images.githubusercontent.com/31783838/115969708-b0425c00-a514-11eb-8d53-5365b38af68a.jpg)

**Comment by ArtyomZorin** [comment]
This change has been made in the latest version (2.8.1)
