### ISSUE TITLE
Suggestion update Zorin OS 15 icons to Zorin OS 16 theme

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#16]
In my opinion, many users will continue to use version 15 of Zorin OS for a while and for them it would be interesting to update the theme of icons taking into account that it has the same aesthetic style, corrects some outdated icons and users give preference to Zorin OS among other linux systems due to its very beautiful interface. I also think that the theme of icons from Zorin OS should follow the trend that Microsoft has followed to make a continuous updating of Windows and Xbox interface. This draws the attention of the media continuously and makes it possible to make improvements gradually with the evaluation of the public's opinion.

**Comment by ArtyomZorin** [comment]
The newest version of the icon theme includes changes which are designed specifically for Zorin OS 16+. This is especially reflected in the colours of the monochrome icons, which were changed to match the foreground colours of the new desktop themes in Zorin OS 16. As a result, backporting the newest icon theme to Zorin OS 15 would make the icons less consistent with the rest of the desktop look.
