### ISSUE TITLE
Missing symbolic link to MPV icon

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#39]
An symlink is missing for "io.mpv.MPV" icon  
![VirtualBoxVM_UlDnTOnvbj](https://user-images.githubusercontent.com/31783838/126815620-dd87b7b4-4c6a-4884-95b8-fdecf78ab8f5.png)

**Comment by ArtyomZorin** [comment]
We've added symlinks for io.mpv.Mpv icons in the latest update.
