### ISSUE TITLE
MPV symbolic link is wrong

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#40]
The correct name is "io.mpv.Mpv" instead of "io.mvp.Mpv"

![VirtualBoxVM_EJN1gzK23n](https://user-images.githubusercontent.com/31783838/127202212-92c3f2cf-ef20-418e-8d4f-29eaadcaa2e5.png)

**Comment by ArtyomZorin** [comment]
Thanks for the heads up! It's been fixed in the latest commit and release (2.8.8).
