### ISSUE TITLE
Missing Audacity icon symbolic link

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-icon-themes#42]
![VirtualBoxVM_0FywhKG91W](https://user-images.githubusercontent.com/31783838/129075038-680baebb-b2ca-4aae-b26a-3ab844225e58.png)

**Comment by ArtyomZorin** [comment]
Thanks! We've fixed this in the latest commit and release (2.8.11).

P.S. You can create a new symbolic link to an icon in the same folder using this command:
`ln -s current-icon.png new-icon-link.png`
